# Generated by Django 2.2.4 on 2022-01-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
